import {
  resolveComponentRef,
  schemaRef,
  type JsonSchema,
  type SchemaComponents,
} from "./json-schema.js";
import { apiBasePath, type RouteDefinition } from "./route-registry.js";
import type { SchemaName } from "./schema-registry.js";
import { componentNameFromRef, printTypeNode } from "./ts-types.js";

const generatedHeader =
  "// @generated by @inpulse/api-contract (pnpm contract:generate).\n" +
  "// 禁止手工修改；产物由 CI 的漂移检查按字节比对。\n";

function isRecord(value: unknown): value is JsonSchema {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function pathParametersOf(path: string): readonly string[] {
  return [...path.matchAll(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g)].map(
    (match) => match[1]!,
  );
}

function successBinding(
  route: RouteDefinition,
):
  | { readonly status: string; readonly schemaRef: SchemaName | undefined }
  | undefined {
  const statuses = Object.keys(route.responses).sort(
    (left, right) => Number(left) - Number(right),
  );
  for (const status of statuses) {
    if (!status.startsWith("2")) {
      continue;
    }
    const binding = route.responses[status]!;
    if ("noBody" in binding) {
      return { status, schemaRef: undefined };
    }
    const json = binding.body.contentTypes.find(
      (entry) => entry.contentType === "application/json",
    );
    if (!json) {
      throw new Error(
        `Route ${route.operationId}: 2xx body must declare application/json for the generated client`,
      );
    }
    return { status, schemaRef: json.schemaRef };
  }
  return undefined;
}

function propertyType(
  schemaRef: string,
  property: string,
  schemas: SchemaComponents,
): string {
  const resolved = resolveComponentRef(schemaRef, schemas.components);
  const properties = resolved.properties;
  if (!isRecord(properties)) {
    throw new Error(
      `Schema ${schemaRef} must be an object to read "${property}"`,
    );
  }
  const node = properties[property];
  if (!isRecord(node)) {
    throw new Error(`Schema ${schemaRef} has no property "${property}"`);
  }
  return printTypeNode(node, schemas.components, 0);
}

function pathExpression(path: string): string {
  const parts = path
    .split(/(\{[A-Za-z_][A-Za-z0-9_]*\})/g)
    .filter((part) => part !== "");
  if (!parts.some((part) => part.startsWith("{"))) {
    return JSON.stringify(path);
  }
  const rendered = parts
    .map((part) =>
      part.startsWith("{")
        ? `\${encodeURIComponent(String(${part.slice(1, -1)}))}`
        : part,
    )
    .join("");
  return `\`${rendered}\``;
}

interface MethodRender {
  readonly signature: string;
  readonly call: string;
  readonly resultType: string;
  readonly usedTypes: readonly string[];
}

function renderMethod(
  route: RouteDefinition,
  schemas: SchemaComponents,
): MethodRender {
  const args: string[] = [];
  const usedTypes: string[] = [];
  const pathParameters = pathParametersOf(route.path);

  for (const name of pathParameters) {
    if (route.request.path === "none") {
      throw new Error(
        `Route ${route.operationId}: path parameter "${name}" has no request.path schema`,
      );
    }
    args.push(
      `${name}: ${propertyType(schemaRef(schemas, route.request.path), name, schemas)}`,
    );
  }

  if (route.request.query !== "none") {
    const queryType = componentNameFromRef(
      schemaRef(schemas, route.request.query),
    );
    args.push(`query: ${queryType}`);
    usedTypes.push(queryType);
  }

  const hasBody = !("noBody" in route.request.body);
  if (hasBody) {
    const json = route.request.body.contentTypes.find(
      (entry) => entry.contentType === "application/json",
    );
    if (!json) {
      throw new Error(
        `Route ${route.operationId}: request body must declare application/json`,
      );
    }
    const bodyType = componentNameFromRef(schemaRef(schemas, json.schemaRef));
    args.push(`body: ${bodyType}`);
    usedTypes.push(bodyType);
  }

  args.push("init?: ApiRequestInit");

  const success = successBinding(route);
  const resultType = success?.schemaRef
    ? componentNameFromRef(schemaRef(schemas, success.schemaRef))
    : "void";
  if (success?.schemaRef) {
    usedTypes.push(resultType);
  }

  const callArguments = [
    "options",
    JSON.stringify(route.method),
    pathExpression(route.path),
    route.request.query === "none" ? '""' : "toQueryString(query)",
    "init",
  ];
  if (hasBody) {
    callArguments.push("body");
  }
  const call =
    resultType === "void"
      ? `return sendEmpty(${callArguments.join(", ")});`
      : `return send<${resultType}>(${callArguments.join(", ")});`;

  return {
    signature: `${route.operationId}(${args.join(", ")})`,
    call,
    resultType,
    usedTypes,
  };
}

export function renderTypesSource(schemas: SchemaComponents): string {
  const blocks = Object.keys(schemas.components)
    .sort()
    .map(
      (name) =>
        `export type ${name} = ${printTypeNode(schemas.components[name]!, schemas.components, 0)};`,
    );
  return `${generatedHeader}\n${blocks.join("\n\n")}\n`;
}

export function renderClientSource(
  routes: readonly RouteDefinition[],
  schemas: SchemaComponents,
): string {
  const methods = [...routes]
    .sort((left, right) => left.operationId.localeCompare(right.operationId))
    .map((route) => renderMethod(route, schemas));

  const usedTypes = new Set<string>();
  for (const method of methods) {
    for (const name of method.usedTypes) {
      usedTypes.add(name);
    }
  }

  // 只生成当前 Registry 真正用到的 helper，避免生成物出现未使用代码。
  const usesSend = methods.some((method) => method.resultType !== "void");
  const usesSendEmpty = methods.some((method) => method.resultType === "void");
  const usesQuery = routes.some((route) => route.request.query !== "none");
  const usesTransport = usesSend || usesSendEmpty;

  const sections: string[] = [];
  if (usedTypes.size > 0) {
    sections.push(
      `import type { ${[...usedTypes].sort().join(", ")} } from "./types";`,
    );
  }
  sections.push(`export const apiBasePath = ${JSON.stringify(apiBasePath)};`);
  sections.push(requestInitTypes);
  sections.push(apiErrorSection);
  if (usesQuery) {
    sections.push(queryStringSection);
  }
  if (usesTransport) {
    sections.push(transportSection);
  }
  if (usesSend) {
    sections.push(sendSection);
  }
  if (usesSendEmpty) {
    sections.push(sendEmptySection);
  }
  sections.push(
    [
      "export interface InpulseApiClient {",
      ...methods.map(
        (method) => `  ${method.signature}: Promise<${method.resultType}>;`,
      ),
      "}",
    ].join("\n"),
  );
  sections.push(
    [
      "export function createApiClient(",
      "  options: ApiClientOptions = {},",
      "): InpulseApiClient {",
      "  return {",
      ...methods.map(
        (method) => `    ${method.signature} {\n      ${method.call}\n    },`,
      ),
      "  };",
      "}",
    ].join("\n"),
  );

  return `${generatedHeader}\n${sections.join("\n\n")}\n`;
}

const requestInitTypes = `export interface ApiRequestInit {
  readonly headers?: Readonly<Record<string, string>>;
  readonly signal?: AbortSignal;
}

export interface ApiClientOptions {
  readonly baseUrl?: string;
  readonly fetchImpl?: typeof fetch;
  readonly defaultHeaders?: Readonly<Record<string, string>>;
}`;

const apiErrorSection = `export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details: Readonly<Record<string, unknown>>;
  readonly requestId: string;

  constructor(status: number, body: unknown) {
    super(errorMessage(status, body));
    this.name = "ApiError";
    this.status = status;
    const envelope = isErrorEnvelope(body) ? body : undefined;
    this.code = envelope?.code ?? "UNEXPECTED_ERROR";
    this.details = envelope?.details ?? {};
    this.requestId = envelope?.requestId ?? "";
  }
}

interface ErrorEnvelope {
  readonly code: string;
  readonly message?: string;
  readonly details: Readonly<Record<string, unknown>>;
  readonly requestId: string;
}

function isErrorEnvelope(value: unknown): value is ErrorEnvelope {
  return (
    typeof value === "object" &&
    value !== null &&
    typeof (value as { code?: unknown }).code === "string"
  );
}

function errorMessage(status: number, body: unknown): string {
  return isErrorEnvelope(body) && typeof body.message === "string"
    ? body.message
    : \`Request failed with status \${status}\`;
}`;

const queryStringSection = `export function toQueryString(query: object): string {
  const parameters = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) {
      continue;
    }
    parameters.append(key, String(value));
  }
  const rendered = parameters.toString();
  return rendered.length === 0 ? "" : \`?\${rendered}\`;
}`;

const transportSection = `async function parsePayload(response: Response): Promise<unknown> {
  const text = await response.text();
  return text.length === 0 ? undefined : (JSON.parse(text) as unknown);
}

async function request(
  options: ApiClientOptions,
  method: string,
  path: string,
  query: string,
  init: ApiRequestInit | undefined,
  body: unknown,
): Promise<Response> {
  const fetchImpl = options.fetchImpl ?? fetch;
  const headers: Record<string, string> = {
    ...options.defaultHeaders,
    ...init?.headers,
  };
  const requestInit: RequestInit = { method, headers };
  if (init?.signal) {
    requestInit.signal = init.signal;
  }
  if (body !== undefined) {
    headers["Content-Type"] = "application/json";
    requestInit.body = JSON.stringify(body);
  }
  const url = \`\${options.baseUrl ?? ""}\${apiBasePath}\${path}\${query}\`;
  return fetchImpl(url, requestInit);
}`;

const sendSection = `async function send<TResult>(
  options: ApiClientOptions,
  method: string,
  path: string,
  query: string,
  init: ApiRequestInit | undefined,
  body?: unknown,
): Promise<TResult> {
  const response = await request(options, method, path, query, init, body);
  const payload = await parsePayload(response);
  if (!response.ok) {
    throw new ApiError(response.status, payload);
  }
  return payload as TResult;
}`;

const sendEmptySection = `async function sendEmpty(
  options: ApiClientOptions,
  method: string,
  path: string,
  query: string,
  init: ApiRequestInit | undefined,
  body?: unknown,
): Promise<void> {
  const response = await request(options, method, path, query, init, body);
  if (!response.ok) {
    throw new ApiError(response.status, await parsePayload(response));
  }
}`;
export function renderIndexSource(): string {
  return `${generatedHeader}
export * from "./client";
export * from "./types";
`;
}
