CREATE SCHEMA IF NOT EXISTS "app" AUTHORIZATION app_owner;
--> statement-breakpoint
CREATE TABLE "app"."audit_chain_heads" (
	"chain_id" text PRIMARY KEY NOT NULL,
	"project_id" integer,
	"last_sequence" bigint DEFAULT 0 NOT NULL,
	"last_hash" "bytea" DEFAULT decode(repeat('00', 32), 'hex') NOT NULL,
	"key_version" smallint NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "audit_chain_heads_chain_check" CHECK ((project_id IS NULL AND chain_id = 'SYSTEM') OR (project_id IS NOT NULL AND chain_id = 'PROJECT:' || project_id::text)),
	CONSTRAINT "audit_chain_heads_sequence_check" CHECK (last_sequence >= 0),
	CONSTRAINT "audit_chain_heads_hash_check" CHECK (octet_length(last_hash) = 32),
	CONSTRAINT "audit_chain_heads_key_version_check" CHECK (key_version > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."audit_logs" (
	"chain_id" text NOT NULL,
	"sequence_no" bigint NOT NULL,
	"project_id" integer,
	"actor_type" text NOT NULL,
	"actor_id" integer,
	"action" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text,
	"event_payload" jsonb NOT NULL,
	"request_id" text NOT NULL,
	"client_request_id" text,
	"ip_address" "inet",
	"user_agent" text,
	"occurred_at" timestamp with time zone NOT NULL,
	"prev_hash" "bytea" NOT NULL,
	"record_hash" "bytea" NOT NULL,
	"key_version" smallint NOT NULL,
	"canonical_version" text NOT NULL,
	CONSTRAINT "audit_logs_pk" PRIMARY KEY("chain_id","sequence_no"),
	CONSTRAINT "audit_logs_chain_hash_unique" UNIQUE("chain_id","record_hash"),
	CONSTRAINT "audit_logs_chain_check" CHECK ((project_id IS NULL AND chain_id = 'SYSTEM') OR (project_id IS NOT NULL AND chain_id = 'PROJECT:' || project_id::text)),
	CONSTRAINT "audit_logs_sequence_check" CHECK (sequence_no > 0),
	CONSTRAINT "audit_logs_actor_check" CHECK ((actor_type = 'USER' AND actor_id IS NOT NULL) OR (actor_type = 'SYSTEM' AND actor_id IS NULL)),
	CONSTRAINT "audit_logs_action_check" CHECK (length(action) BETWEEN 1 AND 200),
	CONSTRAINT "audit_logs_target_type_check" CHECK (length(target_type) BETWEEN 1 AND 100),
	CONSTRAINT "audit_logs_target_id_check" CHECK (target_id IS NULL OR length(target_id) BETWEEN 1 AND 200),
	CONSTRAINT "audit_logs_payload_check" CHECK (jsonb_typeof(event_payload) = 'object' AND pg_column_size(event_payload) <= 1048576),
	CONSTRAINT "audit_logs_request_id_check" CHECK (length(request_id) BETWEEN 1 AND 64 AND request_id ~ '^[A-Za-z0-9._:-]+$'),
	CONSTRAINT "audit_logs_client_request_id_check" CHECK (client_request_id IS NULL OR (length(client_request_id) BETWEEN 1 AND 64 AND client_request_id ~ '^[A-Za-z0-9._:-]+$')),
	CONSTRAINT "audit_logs_user_agent_check" CHECK (user_agent IS NULL OR length(user_agent) <= 1000),
	CONSTRAINT "audit_logs_hashes_check" CHECK (octet_length(prev_hash) = 32 AND octet_length(record_hash) = 32),
	CONSTRAINT "audit_logs_key_version_check" CHECK (key_version > 0),
	CONSTRAINT "audit_logs_canonical_version_check" CHECK (canonical_version = 'JCS-1')
);
--> statement-breakpoint
CREATE TABLE "app"."change_record_feature_impacts" (
	"change_record_id" integer NOT NULL,
	"feature_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"relation_type" text DEFAULT 'IMPACT' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "change_record_feature_impacts_pk" PRIMARY KEY("change_record_id","feature_id"),
	CONSTRAINT "change_record_feature_impacts_type_check" CHECK (relation_type = 'IMPACT')
);
--> statement-breakpoint
CREATE TABLE "app"."change_record_leftover_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."change_record_leftover_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"record_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"created_by" integer NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "change_record_leftovers_id_record_project_unique" UNIQUE("id","record_id","project_id"),
	CONSTRAINT "change_record_leftovers_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "change_record_leftovers_status_check" CHECK (status IN ('ACTIVE', 'CONVERTED', 'RESOLVED')),
	CONSTRAINT "change_record_leftovers_row_version_check" CHECK (row_version > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."change_record_version_leftovers" (
	"record_id" integer NOT NULL,
	"version_no" integer NOT NULL,
	"leftover_item_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"content_snapshot" text NOT NULL,
	CONSTRAINT "change_record_version_leftovers_pk" PRIMARY KEY("record_id","version_no","leftover_item_id"),
	CONSTRAINT "change_record_version_leftovers_content_check" CHECK (length(btrim(content_snapshot)) BETWEEN 1 AND 10000)
);
--> statement-breakpoint
CREATE TABLE "app"."change_record_versions" (
	"record_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"version_no" integer NOT NULL,
	"title_snapshot" text NOT NULL,
	"payload" jsonb NOT NULL,
	"created_by" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "change_record_versions_pk" PRIMARY KEY("record_id","version_no"),
	CONSTRAINT "change_record_versions_project_unique" UNIQUE("record_id","version_no","project_id"),
	CONSTRAINT "change_record_versions_number_check" CHECK (version_no > 0),
	CONSTRAINT "change_record_versions_title_check" CHECK (length(btrim(title_snapshot)) BETWEEN 1 AND 500),
	CONSTRAINT "change_record_versions_payload_check" CHECK (jsonb_typeof(payload) = 'object' AND pg_column_size(payload) <= 1048576)
);
--> statement-breakpoint
CREATE TABLE "app"."change_records" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."change_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"task_id" integer,
	"module_id" integer NOT NULL,
	"feature_id" integer,
	"scope_type" text NOT NULL,
	"code" text,
	"title" text NOT NULL,
	"handler_id" integer NOT NULL,
	"author_id" integer NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"current_version" integer DEFAULT 0 NOT NULL,
	"current_payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"published_at" timestamp with time zone,
	"voided_at" timestamp with time zone,
	"void_reason" text,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "change_records_project_code_unique" UNIQUE("project_id","code"),
	CONSTRAINT "change_records_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "change_records_id_module_project_unique" UNIQUE("id","module_id","project_id"),
	CONSTRAINT "change_records_scope_check" CHECK (scope_type IN ('FEATURE', 'MODULE')),
	CONSTRAINT "change_records_scope_feature_check" CHECK ((scope_type = 'FEATURE' AND feature_id IS NOT NULL) OR (scope_type = 'MODULE' AND feature_id IS NULL)),
	CONSTRAINT "change_records_code_check" CHECK (code IS NULL OR (code ~ '^[A-Z][A-Z0-9_]{1,31}-CR-[1-9][0-9]*$' AND length(code) <= 64)),
	CONSTRAINT "change_records_title_check" CHECK (length(btrim(title)) BETWEEN 1 AND 500),
	CONSTRAINT "change_records_status_check" CHECK (status IN ('DRAFT', 'PUBLISHED', 'VOID')),
	CONSTRAINT "change_records_version_check" CHECK (current_version >= 0),
	CONSTRAINT "change_records_payload_check" CHECK (jsonb_typeof(current_payload) = 'object' AND pg_column_size(current_payload) <= 1048576),
	CONSTRAINT "change_records_void_reason_check" CHECK (void_reason IS NULL OR length(btrim(void_reason)) BETWEEN 1 AND 10000),
	CONSTRAINT "change_records_state_check" CHECK ((status = 'DRAFT' AND code IS NULL AND current_version = 0 AND published_at IS NULL AND voided_at IS NULL AND void_reason IS NULL) OR (status = 'PUBLISHED' AND code IS NOT NULL AND current_version >= 1 AND published_at IS NOT NULL AND ((voided_at IS NULL AND void_reason IS NULL) OR (voided_at IS NOT NULL AND void_reason IS NOT NULL))) OR (status = 'VOID' AND code IS NOT NULL AND current_version >= 1 AND published_at IS NOT NULL AND voided_at IS NOT NULL AND void_reason IS NOT NULL)),
	CONSTRAINT "change_records_timestamp_check" CHECK ((published_at IS NULL OR published_at >= created_at) AND (voided_at IS NULL OR voided_at >= published_at)),
	CONSTRAINT "change_records_row_version_check" CHECK (row_version > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."leftover_task_links" (
	"leftover_item_id" integer PRIMARY KEY NOT NULL,
	"task_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"created_by" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "leftover_task_links_task_unique" UNIQUE("task_id")
);
--> statement-breakpoint
CREATE TABLE "app"."change_record_external_links" (
	"project_id" integer NOT NULL,
	"change_record_id" integer NOT NULL,
	"link_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "change_record_external_links_pk" PRIMARY KEY("project_id","change_record_id","link_id")
);
--> statement-breakpoint
CREATE TABLE "app"."external_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."external_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"display_url" text NOT NULL,
	"normalized_url" text NOT NULL,
	"provider" text DEFAULT 'GITHUB' NOT NULL,
	"kind" text NOT NULL,
	"repository" text,
	"external_number" bigint,
	"external_sha" text,
	"title_snapshot" text,
	"state_snapshot" text,
	"created_by" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "external_links_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "external_links_project_url_unique" UNIQUE("project_id","normalized_url"),
	CONSTRAINT "external_links_display_url_check" CHECK (length(display_url) BETWEEN 1 AND 2048 AND display_url ~ '^https://github[.]com(/|$)'),
	CONSTRAINT "external_links_normalized_url_check" CHECK (length(normalized_url) BETWEEN 1 AND 2048 AND normalized_url ~ '^https://github[.]com(/|$)' AND normalized_url !~ '[#]'),
	CONSTRAINT "external_links_provider_check" CHECK (provider = 'GITHUB'),
	CONSTRAINT "external_links_kind_check" CHECK (kind IN ('ISSUE', 'PULL_REQUEST', 'COMMIT', 'OTHER')),
	CONSTRAINT "external_links_repository_check" CHECK (repository IS NULL OR (length(repository) BETWEEN 3 AND 201 AND repository ~ '^[^/[:space:]]+/[^/[:space:]]+$')),
	CONSTRAINT "external_links_number_check" CHECK (external_number IS NULL OR external_number > 0),
	CONSTRAINT "external_links_sha_check" CHECK (external_sha IS NULL OR external_sha ~ '^[0-9a-fA-F]{7,64}$'),
	CONSTRAINT "external_links_title_check" CHECK (title_snapshot IS NULL OR length(title_snapshot) BETWEEN 1 AND 500),
	CONSTRAINT "external_links_state_check" CHECK (state_snapshot IS NULL OR length(state_snapshot) BETWEEN 1 AND 100)
);
--> statement-breakpoint
CREATE TABLE "app"."feature_external_links" (
	"project_id" integer NOT NULL,
	"feature_id" integer NOT NULL,
	"link_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "feature_external_links_pk" PRIMARY KEY("project_id","feature_id","link_id")
);
--> statement-breakpoint
CREATE TABLE "app"."project_external_links" (
	"project_id" integer NOT NULL,
	"link_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "project_external_links_pk" PRIMARY KEY("project_id","link_id")
);
--> statement-breakpoint
CREATE TABLE "app"."task_external_links" (
	"project_id" integer NOT NULL,
	"task_id" integer NOT NULL,
	"link_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "task_external_links_pk" PRIMARY KEY("project_id","task_id","link_id")
);
--> statement-breakpoint
CREATE TABLE "app"."auth_rate_limit_buckets" (
	"bucket_type" text NOT NULL,
	"dimension_hash" "bytea" NOT NULL,
	"window_started_at" timestamp with time zone NOT NULL,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"blocked_until" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "auth_rate_limit_buckets_pk" PRIMARY KEY("bucket_type","dimension_hash","window_started_at"),
	CONSTRAINT "auth_rate_limit_buckets_type_check" CHECK (bucket_type IN ('ACCOUNT', 'IP', 'GLOBAL', 'MFA')),
	CONSTRAINT "auth_rate_limit_buckets_hash_check" CHECK (octet_length(dimension_hash) = 32),
	CONSTRAINT "auth_rate_limit_buckets_attempts_check" CHECK (attempt_count >= 0),
	CONSTRAINT "auth_rate_limit_buckets_blocked_until_check" CHECK (blocked_until IS NULL OR blocked_until >= window_started_at)
);
--> statement-breakpoint
CREATE TABLE "app"."idempotency_records" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."idempotency_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_id" integer NOT NULL,
	"operation_id" text NOT NULL,
	"idempotency_key" text NOT NULL,
	"idempotency_contract_version" text NOT NULL,
	"request_hash" "bytea" NOT NULL,
	"request_hash_key_version" smallint NOT NULL,
	"state" text DEFAULT 'PENDING' NOT NULL,
	"response_status" integer,
	"response_schema_ref" text,
	"replay_policy_version" text,
	"replay_auth_policy_version" text,
	"replay_auth_context" jsonb,
	"response_has_body" boolean,
	"response_body" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "idempotency_records_request_unique" UNIQUE("actor_id","operation_id","idempotency_key"),
	CONSTRAINT "idempotency_records_operation_check" CHECK (length(operation_id) BETWEEN 1 AND 200),
	CONSTRAINT "idempotency_records_key_check" CHECK (length(idempotency_key) BETWEEN 16 AND 128),
	CONSTRAINT "idempotency_records_contract_check" CHECK (length(idempotency_contract_version) BETWEEN 1 AND 100),
	CONSTRAINT "idempotency_records_hash_check" CHECK (octet_length(request_hash) = 32),
	CONSTRAINT "idempotency_records_key_version_check" CHECK (request_hash_key_version > 0),
	CONSTRAINT "idempotency_records_state_check" CHECK (state IN ('PENDING', 'SUCCEEDED')),
	CONSTRAINT "idempotency_records_expiry_check" CHECK (expires_at > created_at),
	CONSTRAINT "idempotency_records_response_check" CHECK ((state = 'PENDING' AND response_status IS NULL AND response_schema_ref IS NULL AND replay_policy_version IS NULL AND replay_auth_policy_version IS NULL AND replay_auth_context IS NULL AND response_has_body IS NULL AND response_body IS NULL) OR (state = 'SUCCEEDED' AND response_status BETWEEN 200 AND 299 AND replay_policy_version IS NOT NULL AND replay_auth_policy_version IS NOT NULL AND replay_auth_context IS NOT NULL AND jsonb_typeof(replay_auth_context) = 'object' AND response_has_body IS NOT NULL AND ((response_has_body AND response_schema_ref IS NOT NULL AND response_body IS NOT NULL) OR (NOT response_has_body AND response_schema_ref IS NULL AND response_body IS NULL))))
);
--> statement-breakpoint
CREATE TABLE "app"."mfa_recovery_codes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."mfa_recovery_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"batch_version" integer NOT NULL,
	"code_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"used_at" timestamp with time zone,
	CONSTRAINT "mfa_recovery_codes_user_hash_unique" UNIQUE("user_id","code_hash"),
	CONSTRAINT "mfa_recovery_codes_batch_check" CHECK (batch_version > 0),
	CONSTRAINT "mfa_recovery_codes_argon2id_check" CHECK (code_hash LIKE '$argon2id$%' AND length(code_hash) <= 1024),
	CONSTRAINT "mfa_recovery_codes_used_at_check" CHECK (used_at IS NULL OR used_at >= created_at)
);
--> statement-breakpoint
CREATE TABLE "app"."preauth_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."preauth_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"token_hash" "bytea" NOT NULL,
	"token_hash_key_version" smallint NOT NULL,
	"csrf_token_hash" "bytea" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	CONSTRAINT "preauth_sessions_token_hash_unique" UNIQUE("token_hash"),
	CONSTRAINT "preauth_sessions_csrf_hash_unique" UNIQUE("csrf_token_hash"),
	CONSTRAINT "preauth_sessions_hashes_check" CHECK (octet_length(token_hash) = 32 AND octet_length(csrf_token_hash) = 32),
	CONSTRAINT "preauth_sessions_key_version_check" CHECK (token_hash_key_version > 0),
	CONSTRAINT "preauth_sessions_expiry_check" CHECK (expires_at > created_at AND expires_at <= created_at + INTERVAL '10 minutes'),
	CONSTRAINT "preauth_sessions_consumed_at_check" CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);
--> statement-breakpoint
CREATE TABLE "app"."session_csrf_tokens" (
	"session_id" bigint NOT NULL,
	"token_hash" "bytea" NOT NULL,
	"issued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "session_csrf_tokens_pk" PRIMARY KEY("session_id","token_hash"),
	CONSTRAINT "session_csrf_tokens_hash_unique" UNIQUE("token_hash"),
	CONSTRAINT "session_csrf_tokens_hash_check" CHECK (octet_length(token_hash) = 32),
	CONSTRAINT "session_csrf_tokens_expiry_check" CHECK (expires_at > issued_at)
);
--> statement-breakpoint
CREATE TABLE "app"."user_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."user_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"token_hash" "bytea" NOT NULL,
	"token_hash_key_version" smallint NOT NULL,
	"auth_version_at_issue" integer NOT NULL,
	"auth_state" text NOT NULL,
	"recovery_rotation_generation" integer DEFAULT 0 NOT NULL,
	"recovery_rotation_consumed_generation" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"idle_expires_at" timestamp with time zone NOT NULL,
	"absolute_expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"reauthenticated_at" timestamp with time zone,
	"mfa_verified_at" timestamp with time zone,
	CONSTRAINT "user_sessions_token_hash_unique" UNIQUE("token_hash"),
	CONSTRAINT "user_sessions_token_hash_check" CHECK (octet_length(token_hash) = 32),
	CONSTRAINT "user_sessions_token_key_version_check" CHECK (token_hash_key_version > 0),
	CONSTRAINT "user_sessions_auth_version_check" CHECK (auth_version_at_issue > 0),
	CONSTRAINT "user_sessions_auth_state_check" CHECK (auth_state IN ('AUTHENTICATED', 'MFA_ENROLLMENT', 'MFA_CHALLENGE', 'RECOVERY_CHALLENGE')),
	CONSTRAINT "user_sessions_rotation_check" CHECK (recovery_rotation_generation >= 0 AND recovery_rotation_consumed_generation >= 0 AND recovery_rotation_consumed_generation <= recovery_rotation_generation),
	CONSTRAINT "user_sessions_expiry_order_check" CHECK (idle_expires_at <= absolute_expires_at),
	CONSTRAINT "user_sessions_revoked_at_check" CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
--> statement-breakpoint
CREATE TABLE "app"."user_totp_factors" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"status" text NOT NULL,
	"enrollment_generation" integer NOT NULL,
	"key_version" smallint NOT NULL,
	"nonce" "bytea" NOT NULL,
	"ciphertext" "bytea" NOT NULL,
	"auth_tag" "bytea" NOT NULL,
	"last_accepted_step" bigint,
	"enrolled_at" timestamp with time zone,
	"disabled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_totp_factors_status_check" CHECK (status IN ('ENROLLING', 'ACTIVE', 'DISABLED')),
	CONSTRAINT "user_totp_factors_generation_check" CHECK (enrollment_generation > 0),
	CONSTRAINT "user_totp_factors_key_version_check" CHECK (key_version > 0),
	CONSTRAINT "user_totp_factors_crypto_check" CHECK (octet_length(nonce) BETWEEN 12 AND 32 AND octet_length(ciphertext) > 0 AND octet_length(auth_tag) BETWEEN 12 AND 32),
	CONSTRAINT "user_totp_factors_state_check" CHECK ((status = 'ENROLLING' AND enrolled_at IS NULL AND disabled_at IS NULL) OR (status = 'ACTIVE' AND enrolled_at IS NOT NULL AND disabled_at IS NULL) OR (status = 'DISABLED' AND disabled_at IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "app"."users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"login_name" text NOT NULL,
	"name" text NOT NULL,
	"email" text,
	"avatar_url" text,
	"password_hash" text NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"auth_version" integer DEFAULT 1 NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"password_changed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"disabled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_id_unique" UNIQUE("id"),
	CONSTRAINT "users_login_name_length_check" CHECK (length(btrim(login_name)) BETWEEN 1 AND 100),
	CONSTRAINT "users_name_length_check" CHECK (length(btrim(name)) BETWEEN 1 AND 200),
	CONSTRAINT "users_email_check" CHECK (email IS NULL OR length(btrim(email)) BETWEEN 3 AND 320),
	CONSTRAINT "users_avatar_url_check" CHECK (avatar_url IS NULL OR length(avatar_url) BETWEEN 1 AND 2048),
	CONSTRAINT "users_password_hash_check" CHECK (length(password_hash) BETWEEN 20 AND 1024),
	CONSTRAINT "users_status_check" CHECK (status IN ('ACTIVE', 'DISABLED')),
	CONSTRAINT "users_auth_version_check" CHECK (auth_version > 0),
	CONSTRAINT "users_row_version_check" CHECK (row_version > 0),
	CONSTRAINT "users_disabled_state_check" CHECK ((status = 'ACTIVE' AND disabled_at IS NULL) OR (status = 'DISABLED' AND disabled_at IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "app"."activity_projection" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."activity_projection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"source_chain_id" text NOT NULL,
	"source_sequence" bigint NOT NULL,
	"source_entity_type" text NOT NULL,
	"source_entity_id" integer NOT NULL,
	"activity_type" text NOT NULL,
	"actor_id" integer,
	"summary" text NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"visibility_scope" text DEFAULT 'MEMBER' NOT NULL,
	"source_status" text NOT NULL,
	"source_row_version" integer NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	CONSTRAINT "activity_projection_source_unique" UNIQUE("source_chain_id","source_sequence"),
	CONSTRAINT "activity_projection_entity_type_check" CHECK (length(source_entity_type) BETWEEN 1 AND 100),
	CONSTRAINT "activity_projection_activity_type_check" CHECK (length(activity_type) BETWEEN 1 AND 100),
	CONSTRAINT "activity_projection_summary_check" CHECK (length(btrim(summary)) BETWEEN 1 AND 1000),
	CONSTRAINT "activity_projection_metadata_check" CHECK (jsonb_typeof(metadata) = 'object' AND pg_column_size(metadata) <= 65536),
	CONSTRAINT "activity_projection_visibility_check" CHECK (visibility_scope IN ('MEMBER', 'ADMIN_ONLY')),
	CONSTRAINT "activity_projection_source_status_check" CHECK (length(source_status) BETWEEN 1 AND 50),
	CONSTRAINT "activity_projection_source_version_check" CHECK (source_row_version > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."code_sequences" (
	"project_id" integer NOT NULL,
	"entity_type" text NOT NULL,
	"last_number" integer NOT NULL,
	CONSTRAINT "code_sequences_pk" PRIMARY KEY("project_id","entity_type"),
	CONSTRAINT "code_sequences_entity_check" CHECK (entity_type IN ('FEATURE', 'TASK', 'CHANGE_RECORD', 'TASK_GROUP')),
	CONSTRAINT "code_sequences_number_check" CHECK (last_number > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"recipient_id" integer NOT NULL,
	"project_id" integer,
	"source_chain_id" text NOT NULL,
	"source_sequence" bigint NOT NULL,
	"notification_type" text NOT NULL,
	"title" text NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"target_path" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"read_at" timestamp with time zone,
	CONSTRAINT "notifications_source_recipient_type_unique" UNIQUE("source_chain_id","source_sequence","recipient_id","notification_type"),
	CONSTRAINT "notifications_type_check" CHECK (length(notification_type) BETWEEN 1 AND 100),
	CONSTRAINT "notifications_title_check" CHECK (length(btrim(title)) BETWEEN 1 AND 500),
	CONSTRAINT "notifications_body_check" CHECK (length(body) <= 5000),
	CONSTRAINT "notifications_target_path_check" CHECK (target_path IS NULL OR (length(target_path) BETWEEN 1 AND 2048 AND target_path LIKE '/%')),
	CONSTRAINT "notifications_read_at_check" CHECK (read_at IS NULL OR read_at >= created_at)
);
--> statement-breakpoint
CREATE TABLE "app"."search_projection" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."search_projection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" integer NOT NULL,
	"title" text NOT NULL,
	"summary" text DEFAULT '' NOT NULL,
	"raw_text" text NOT NULL,
	"normalized_search_text" text NOT NULL,
	"visibility_scope" text DEFAULT 'MEMBER' NOT NULL,
	"source_status" text NOT NULL,
	"source_row_version" integer NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "search_projection_entity_unique" UNIQUE("project_id","entity_type","entity_id"),
	CONSTRAINT "search_projection_entity_type_check" CHECK (entity_type IN ('PROJECT', 'MODULE', 'FEATURE', 'TASK', 'CHANGE_RECORD', 'EXTERNAL_LINK', 'TASK_GROUP')),
	CONSTRAINT "search_projection_title_check" CHECK (length(btrim(title)) BETWEEN 1 AND 500),
	CONSTRAINT "search_projection_summary_check" CHECK (length(summary) <= 5000),
	CONSTRAINT "search_projection_raw_text_check" CHECK (length(raw_text) BETWEEN 1 AND 100000),
	CONSTRAINT "search_projection_normalized_text_check" CHECK (length(normalized_search_text) BETWEEN 1 AND 100000),
	CONSTRAINT "search_projection_visibility_check" CHECK (visibility_scope IN ('MEMBER', 'ADMIN_ONLY', 'HIDDEN')),
	CONSTRAINT "search_projection_source_status_check" CHECK (length(source_status) BETWEEN 1 AND 50),
	CONSTRAINT "search_projection_source_version_check" CHECK (source_row_version > 0)
);
--> statement-breakpoint
CREATE TABLE "app"."project_members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."project_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"user_id" integer NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"removed_at" timestamp with time zone,
	CONSTRAINT "project_members_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "project_members_status_check" CHECK (status IN ('ACTIVE', 'REMOVED')),
	CONSTRAINT "project_members_state_check" CHECK ((status = 'ACTIVE' AND removed_at IS NULL) OR (status = 'REMOVED' AND removed_at IS NOT NULL AND removed_at >= joined_at))
);
--> statement-breakpoint
CREATE TABLE "app"."projects" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"created_by" integer NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "projects_code_unique" UNIQUE("code"),
	CONSTRAINT "projects_id_unique" UNIQUE("id"),
	CONSTRAINT "projects_code_check" CHECK (code ~ '^[A-Z][A-Z0-9_]{1,31}$'),
	CONSTRAINT "projects_name_check" CHECK (length(btrim(name)) BETWEEN 1 AND 200),
	CONSTRAINT "projects_description_check" CHECK (length(description) <= 20000),
	CONSTRAINT "projects_status_check" CHECK (status IN ('ACTIVE', 'ARCHIVED')),
	CONSTRAINT "projects_row_version_check" CHECK (row_version > 0),
	CONSTRAINT "projects_archive_state_check" CHECK ((status = 'ACTIVE' AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_at IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "app"."task_group_members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."task_group_members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"group_id" integer NOT NULL,
	"task_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"role" text NOT NULL,
	"source_kind" text,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"original_work_status" text,
	"original_assignee_id" integer,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"detached_at" timestamp with time zone,
	"detached_by" integer,
	"detach_reason" text,
	CONSTRAINT "task_group_members_group_task_unique" UNIQUE("project_id","group_id","task_id"),
	CONSTRAINT "task_group_members_role_check" CHECK (role IN ('MAIN', 'SOURCE')),
	CONSTRAINT "task_group_members_source_kind_check" CHECK (source_kind IS NULL OR source_kind IN ('ACTIVE', 'HISTORICAL')),
	CONSTRAINT "task_group_members_status_check" CHECK (status IN ('ACTIVE', 'DETACHED')),
	CONSTRAINT "task_group_members_original_status_check" CHECK (original_work_status IS NULL OR original_work_status IN ('TODO', 'DONE', 'CANCELED')),
	CONSTRAINT "task_group_members_snapshot_check" CHECK ((role = 'MAIN' AND source_kind IS NULL AND original_work_status IS NULL AND original_assignee_id IS NULL) OR (role = 'SOURCE' AND source_kind IS NOT NULL AND original_work_status IS NOT NULL AND original_assignee_id IS NOT NULL)),
	CONSTRAINT "task_group_members_detach_state_check" CHECK ((status = 'ACTIVE' AND detached_at IS NULL AND detached_by IS NULL AND detach_reason IS NULL) OR (status = 'DETACHED' AND detached_at IS NOT NULL AND detached_by IS NOT NULL AND detach_reason IS NOT NULL AND length(btrim(detach_reason)) BETWEEN 1 AND 10000)),
	CONSTRAINT "task_group_members_detach_time_check" CHECK (detached_at IS NULL OR detached_at >= joined_at)
);
--> statement-breakpoint
CREATE TABLE "app"."task_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."task_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"created_by" integer NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"closed_at" timestamp with time zone,
	CONSTRAINT "task_groups_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "task_groups_project_code_unique" UNIQUE("project_id","code"),
	CONSTRAINT "task_groups_code_check" CHECK (code ~ '^[A-Z][A-Z0-9_]{1,31}-TG-[1-9][0-9]*$' AND length(code) <= 64),
	CONSTRAINT "task_groups_name_check" CHECK (length(btrim(name)) BETWEEN 1 AND 500),
	CONSTRAINT "task_groups_status_check" CHECK (status IN ('ACTIVE', 'CLOSED')),
	CONSTRAINT "task_groups_row_version_check" CHECK (row_version > 0),
	CONSTRAINT "task_groups_close_state_check" CHECK ((status = 'ACTIVE' AND closed_at IS NULL) OR (status = 'CLOSED' AND closed_at IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "app"."features" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."features_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"current_behavior" text DEFAULT '' NOT NULL,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"created_by" integer NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "features_project_code_unique" UNIQUE("project_id","code"),
	CONSTRAINT "features_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "features_id_module_project_unique" UNIQUE("id","module_id","project_id"),
	CONSTRAINT "features_code_check" CHECK (code ~ '^[A-Z][A-Z0-9_]{1,31}-F-[1-9][0-9]*$' AND length(code) <= 64),
	CONSTRAINT "features_name_check" CHECK (length(btrim(name)) BETWEEN 1 AND 500),
	CONSTRAINT "features_behavior_check" CHECK (length(current_behavior) <= 50000),
	CONSTRAINT "features_tags_check" CHECK (cardinality(tags) <= 50 AND array_position(tags, NULL) IS NULL),
	CONSTRAINT "features_status_check" CHECK (status IN ('ACTIVE', 'ARCHIVED')),
	CONSTRAINT "features_row_version_check" CHECK (row_version > 0),
	CONSTRAINT "features_archive_state_check" CHECK ((status = 'ACTIVE' AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_at IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "app"."modules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."modules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"kind" text DEFAULT 'NORMAL' NOT NULL,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_by" integer NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "modules_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "modules_name_check" CHECK (length(btrim(name)) BETWEEN 1 AND 200),
	CONSTRAINT "modules_description_check" CHECK (length(description) <= 20000),
	CONSTRAINT "modules_kind_check" CHECK (kind IN ('NORMAL', 'UNCLASSIFIED')),
	CONSTRAINT "modules_status_check" CHECK (status IN ('ACTIVE', 'ARCHIVED')),
	CONSTRAINT "modules_sort_order_check" CHECK (sort_order >= 0),
	CONSTRAINT "modules_row_version_check" CHECK (row_version > 0),
	CONSTRAINT "modules_archive_state_check" CHECK ((status = 'ACTIVE' AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_at IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "app"."task_feature_impacts" (
	"task_id" integer NOT NULL,
	"feature_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"relation_type" text DEFAULT 'IMPACT' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "task_feature_impacts_pk" PRIMARY KEY("task_id","feature_id"),
	CONSTRAINT "task_feature_impacts_type_check" CHECK (relation_type = 'IMPACT')
);
--> statement-breakpoint
CREATE TABLE "app"."task_status_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."task_status_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"task_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"from_work_status" text,
	"to_work_status" text NOT NULL,
	"completed_at_snapshot" timestamp with time zone,
	"completion_note_snapshot" text,
	"reason" text,
	"changed_by" integer NOT NULL,
	"changed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "task_status_history_from_check" CHECK (from_work_status IS NULL OR from_work_status IN ('TODO', 'DONE', 'CANCELED')),
	CONSTRAINT "task_status_history_to_check" CHECK (to_work_status IN ('TODO', 'DONE', 'CANCELED')),
	CONSTRAINT "task_status_history_transition_check" CHECK (from_work_status IS NULL OR from_work_status <> to_work_status),
	CONSTRAINT "task_status_history_completion_check" CHECK (((from_work_status = 'DONE' OR to_work_status = 'DONE') AND completed_at_snapshot IS NOT NULL) OR ((from_work_status IS DISTINCT FROM 'DONE' AND to_work_status <> 'DONE') AND completed_at_snapshot IS NULL)),
	CONSTRAINT "task_status_history_note_check" CHECK (completion_note_snapshot IS NULL OR length(btrim(completion_note_snapshot)) BETWEEN 1 AND 10000),
	CONSTRAINT "task_status_history_reason_check" CHECK (reason IS NULL OR length(btrim(reason)) BETWEEN 1 AND 10000)
);
--> statement-breakpoint
CREATE TABLE "app"."tasks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"module_id" integer NOT NULL,
	"feature_id" integer,
	"scope_type" text NOT NULL,
	"code" text NOT NULL,
	"title" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"assignee_id" integer NOT NULL,
	"creator_id" integer NOT NULL,
	"priority" text DEFAULT 'NORMAL' NOT NULL,
	"work_status" text DEFAULT 'TODO' NOT NULL,
	"lifecycle_status" text DEFAULT 'ACTIVE' NOT NULL,
	"completion_note" text,
	"completed_at" timestamp with time zone,
	"due_at" timestamp with time zone,
	"row_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tasks_project_code_unique" UNIQUE("project_id","code"),
	CONSTRAINT "tasks_id_project_unique" UNIQUE("id","project_id"),
	CONSTRAINT "tasks_id_module_project_unique" UNIQUE("id","module_id","project_id"),
	CONSTRAINT "tasks_scope_check" CHECK (scope_type IN ('FEATURE', 'MODULE')),
	CONSTRAINT "tasks_scope_feature_check" CHECK ((scope_type = 'FEATURE' AND feature_id IS NOT NULL) OR (scope_type = 'MODULE' AND feature_id IS NULL)),
	CONSTRAINT "tasks_code_check" CHECK (code ~ '^[A-Z][A-Z0-9_]{1,31}-T-[1-9][0-9]*$' AND length(code) <= 64),
	CONSTRAINT "tasks_title_check" CHECK (length(btrim(title)) BETWEEN 1 AND 500),
	CONSTRAINT "tasks_description_check" CHECK (length(description) <= 50000),
	CONSTRAINT "tasks_priority_check" CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
	CONSTRAINT "tasks_work_status_check" CHECK (work_status IN ('TODO', 'DONE', 'CANCELED')),
	CONSTRAINT "tasks_lifecycle_status_check" CHECK (lifecycle_status IN ('ACTIVE', 'ARCHIVED', 'INVALID')),
	CONSTRAINT "tasks_completion_note_check" CHECK (completion_note IS NULL OR length(btrim(completion_note)) BETWEEN 1 AND 10000),
	CONSTRAINT "tasks_completion_state_check" CHECK ((work_status = 'DONE' AND completed_at IS NOT NULL) OR (work_status <> 'DONE' AND completed_at IS NULL)),
	CONSTRAINT "tasks_row_version_check" CHECK (row_version > 0)
);
--> statement-breakpoint
ALTER TABLE "app"."audit_chain_heads" ADD CONSTRAINT "audit_chain_heads_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."audit_logs" ADD CONSTRAINT "audit_logs_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."audit_logs" ADD CONSTRAINT "audit_logs_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."audit_logs" ADD CONSTRAINT "audit_logs_chain_fk" FOREIGN KEY ("chain_id") REFERENCES "app"."audit_chain_heads"("chain_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_feature_impacts" ADD CONSTRAINT "change_record_feature_impacts_record_fk" FOREIGN KEY ("change_record_id","module_id","project_id") REFERENCES "app"."change_records"("id","module_id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_feature_impacts" ADD CONSTRAINT "change_record_feature_impacts_feature_fk" FOREIGN KEY ("feature_id","module_id","project_id") REFERENCES "app"."features"("id","module_id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_leftover_items" ADD CONSTRAINT "change_record_leftover_items_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_leftover_items" ADD CONSTRAINT "change_record_leftovers_record_fk" FOREIGN KEY ("record_id","project_id") REFERENCES "app"."change_records"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_version_leftovers" ADD CONSTRAINT "change_record_version_leftovers_version_fk" FOREIGN KEY ("record_id","version_no","project_id") REFERENCES "app"."change_record_versions"("record_id","version_no","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_version_leftovers" ADD CONSTRAINT "change_record_version_leftovers_item_fk" FOREIGN KEY ("leftover_item_id","record_id","project_id") REFERENCES "app"."change_record_leftover_items"("id","record_id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_versions" ADD CONSTRAINT "change_record_versions_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_versions" ADD CONSTRAINT "change_record_versions_record_fk" FOREIGN KEY ("record_id","project_id") REFERENCES "app"."change_records"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_records" ADD CONSTRAINT "change_records_handler_id_users_id_fk" FOREIGN KEY ("handler_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_records" ADD CONSTRAINT "change_records_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_records" ADD CONSTRAINT "change_records_module_project_fk" FOREIGN KEY ("module_id","project_id") REFERENCES "app"."modules"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_records" ADD CONSTRAINT "change_records_task_project_fk" FOREIGN KEY ("task_id","project_id") REFERENCES "app"."tasks"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_records" ADD CONSTRAINT "change_records_feature_module_project_fk" FOREIGN KEY ("feature_id","module_id","project_id") REFERENCES "app"."features"("id","module_id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."leftover_task_links" ADD CONSTRAINT "leftover_task_links_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."leftover_task_links" ADD CONSTRAINT "leftover_task_links_item_fk" FOREIGN KEY ("leftover_item_id","project_id") REFERENCES "app"."change_record_leftover_items"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."leftover_task_links" ADD CONSTRAINT "leftover_task_links_task_fk" FOREIGN KEY ("task_id","project_id") REFERENCES "app"."tasks"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_external_links" ADD CONSTRAINT "change_record_external_links_record_fk" FOREIGN KEY ("change_record_id","project_id") REFERENCES "app"."change_records"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."change_record_external_links" ADD CONSTRAINT "change_record_external_links_link_fk" FOREIGN KEY ("link_id","project_id") REFERENCES "app"."external_links"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."external_links" ADD CONSTRAINT "external_links_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."external_links" ADD CONSTRAINT "external_links_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."feature_external_links" ADD CONSTRAINT "feature_external_links_feature_fk" FOREIGN KEY ("feature_id","project_id") REFERENCES "app"."features"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."feature_external_links" ADD CONSTRAINT "feature_external_links_link_fk" FOREIGN KEY ("link_id","project_id") REFERENCES "app"."external_links"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."project_external_links" ADD CONSTRAINT "project_external_links_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."project_external_links" ADD CONSTRAINT "project_external_links_link_fk" FOREIGN KEY ("link_id","project_id") REFERENCES "app"."external_links"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_external_links" ADD CONSTRAINT "task_external_links_task_fk" FOREIGN KEY ("task_id","project_id") REFERENCES "app"."tasks"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_external_links" ADD CONSTRAINT "task_external_links_link_fk" FOREIGN KEY ("link_id","project_id") REFERENCES "app"."external_links"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."idempotency_records" ADD CONSTRAINT "idempotency_records_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."mfa_recovery_codes" ADD CONSTRAINT "mfa_recovery_codes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."session_csrf_tokens" ADD CONSTRAINT "session_csrf_tokens_session_id_user_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "app"."user_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_sessions" ADD CONSTRAINT "user_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_totp_factors" ADD CONSTRAINT "user_totp_factors_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."activity_projection" ADD CONSTRAINT "activity_projection_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."activity_projection" ADD CONSTRAINT "activity_projection_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."activity_projection" ADD CONSTRAINT "activity_projection_source_audit_fk" FOREIGN KEY ("source_chain_id","source_sequence") REFERENCES "app"."audit_logs"("chain_id","sequence_no") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."code_sequences" ADD CONSTRAINT "code_sequences_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."notifications" ADD CONSTRAINT "notifications_recipient_id_users_id_fk" FOREIGN KEY ("recipient_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."notifications" ADD CONSTRAINT "notifications_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."notifications" ADD CONSTRAINT "notifications_source_audit_fk" FOREIGN KEY ("source_chain_id","source_sequence") REFERENCES "app"."audit_logs"("chain_id","sequence_no") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."search_projection" ADD CONSTRAINT "search_projection_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."project_members" ADD CONSTRAINT "project_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."project_members" ADD CONSTRAINT "project_members_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."projects" ADD CONSTRAINT "projects_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_group_members" ADD CONSTRAINT "task_group_members_original_assignee_id_users_id_fk" FOREIGN KEY ("original_assignee_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_group_members" ADD CONSTRAINT "task_group_members_detached_by_users_id_fk" FOREIGN KEY ("detached_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_group_members" ADD CONSTRAINT "task_group_members_group_fk" FOREIGN KEY ("group_id","project_id") REFERENCES "app"."task_groups"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_group_members" ADD CONSTRAINT "task_group_members_task_fk" FOREIGN KEY ("task_id","project_id") REFERENCES "app"."tasks"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_groups" ADD CONSTRAINT "task_groups_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_groups" ADD CONSTRAINT "task_groups_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."features" ADD CONSTRAINT "features_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."features" ADD CONSTRAINT "features_module_project_fk" FOREIGN KEY ("module_id","project_id") REFERENCES "app"."modules"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."modules" ADD CONSTRAINT "modules_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."modules" ADD CONSTRAINT "modules_project_fk" FOREIGN KEY ("project_id") REFERENCES "app"."projects"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_feature_impacts" ADD CONSTRAINT "task_feature_impacts_task_fk" FOREIGN KEY ("task_id","module_id","project_id") REFERENCES "app"."tasks"("id","module_id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_feature_impacts" ADD CONSTRAINT "task_feature_impacts_feature_fk" FOREIGN KEY ("feature_id","module_id","project_id") REFERENCES "app"."features"("id","module_id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_status_history" ADD CONSTRAINT "task_status_history_changed_by_users_id_fk" FOREIGN KEY ("changed_by") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."task_status_history" ADD CONSTRAINT "task_status_history_task_fk" FOREIGN KEY ("task_id","project_id") REFERENCES "app"."tasks"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."tasks" ADD CONSTRAINT "tasks_assignee_id_users_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."tasks" ADD CONSTRAINT "tasks_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "app"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."tasks" ADD CONSTRAINT "tasks_module_project_fk" FOREIGN KEY ("module_id","project_id") REFERENCES "app"."modules"("id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."tasks" ADD CONSTRAINT "tasks_feature_module_project_fk" FOREIGN KEY ("feature_id","module_id","project_id") REFERENCES "app"."features"("id","module_id","project_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "audit_logs_chain_prev_hash_unique" ON "app"."audit_logs" USING btree ("chain_id","prev_hash") WHERE sequence_no > 1;--> statement-breakpoint
CREATE INDEX "audit_logs_project_time_idx" ON "app"."audit_logs" USING btree ("project_id","occurred_at","sequence_no");--> statement-breakpoint
CREATE INDEX "audit_logs_actor_time_idx" ON "app"."audit_logs" USING btree ("actor_id","occurred_at","sequence_no");--> statement-breakpoint
CREATE INDEX "change_record_leftovers_record_status_idx" ON "app"."change_record_leftover_items" USING btree ("project_id","record_id","status","id");--> statement-breakpoint
CREATE INDEX "change_records_project_task_idx" ON "app"."change_records" USING btree ("project_id","task_id","id") WHERE task_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "change_records_project_status_idx" ON "app"."change_records" USING btree ("project_id","status","id");--> statement-breakpoint
CREATE INDEX "auth_rate_limit_buckets_cleanup_idx" ON "app"."auth_rate_limit_buckets" USING btree ("window_started_at","blocked_until");--> statement-breakpoint
CREATE INDEX "idempotency_records_expiry_idx" ON "app"."idempotency_records" USING btree ("expires_at","id");--> statement-breakpoint
CREATE INDEX "mfa_recovery_codes_user_active_idx" ON "app"."mfa_recovery_codes" USING btree ("user_id","batch_version") WHERE used_at IS NULL;--> statement-breakpoint
CREATE INDEX "preauth_sessions_expiry_idx" ON "app"."preauth_sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "session_csrf_tokens_expiry_idx" ON "app"."session_csrf_tokens" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "user_sessions_user_active_idx" ON "app"."user_sessions" USING btree ("user_id","absolute_expires_at") WHERE revoked_at IS NULL;--> statement-breakpoint
CREATE INDEX "user_sessions_expiry_idx" ON "app"."user_sessions" USING btree ("absolute_expires_at","idle_expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "users_login_name_normalized_unique" ON "app"."users" USING btree (lower(btrim(login_name)));--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_normalized_unique" ON "app"."users" USING btree (lower(btrim(email))) WHERE email IS NOT NULL;--> statement-breakpoint
CREATE INDEX "activity_projection_project_cursor_idx" ON "app"."activity_projection" USING btree ("project_id","occurred_at","id");--> statement-breakpoint
CREATE INDEX "activity_projection_entity_idx" ON "app"."activity_projection" USING btree ("project_id","source_entity_type","source_entity_id","occurred_at");--> statement-breakpoint
CREATE INDEX "notifications_recipient_cursor_idx" ON "app"."notifications" USING btree ("recipient_id","created_at","id");--> statement-breakpoint
CREATE INDEX "notifications_recipient_unread_idx" ON "app"."notifications" USING btree ("recipient_id","created_at","id") WHERE read_at IS NULL;--> statement-breakpoint
CREATE INDEX "search_projection_project_type_idx" ON "app"."search_projection" USING btree ("project_id","entity_type","visibility_scope","id");--> statement-breakpoint
CREATE UNIQUE INDEX "project_members_active_unique" ON "app"."project_members" USING btree ("project_id","user_id") WHERE status = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "project_members_user_active_idx" ON "app"."project_members" USING btree ("user_id","project_id") WHERE status = 'ACTIVE';--> statement-breakpoint
CREATE UNIQUE INDEX "task_group_members_one_active_group_unique" ON "app"."task_group_members" USING btree ("task_id") WHERE status = 'ACTIVE';--> statement-breakpoint
CREATE UNIQUE INDEX "task_group_members_one_active_main_unique" ON "app"."task_group_members" USING btree ("group_id") WHERE status = 'ACTIVE' AND role = 'MAIN';--> statement-breakpoint
CREATE INDEX "task_group_members_group_status_idx" ON "app"."task_group_members" USING btree ("project_id","group_id","status","id");--> statement-breakpoint
CREATE INDEX "task_groups_project_status_idx" ON "app"."task_groups" USING btree ("project_id","status","id");--> statement-breakpoint
CREATE INDEX "features_module_status_idx" ON "app"."features" USING btree ("project_id","module_id","status","id");--> statement-breakpoint
CREATE UNIQUE INDEX "modules_name_project_unique" ON "app"."modules" USING btree ("project_id",lower(btrim(name)));--> statement-breakpoint
CREATE UNIQUE INDEX "modules_one_unclassified_unique" ON "app"."modules" USING btree ("project_id") WHERE kind = 'UNCLASSIFIED';--> statement-breakpoint
CREATE INDEX "modules_project_order_idx" ON "app"."modules" USING btree ("project_id","sort_order","id");--> statement-breakpoint
CREATE INDEX "task_status_history_task_time_idx" ON "app"."task_status_history" USING btree ("project_id","task_id","changed_at","id");--> statement-breakpoint
CREATE INDEX "tasks_project_status_idx" ON "app"."tasks" USING btree ("project_id","lifecycle_status","work_status","id");--> statement-breakpoint
CREATE INDEX "tasks_assignee_status_idx" ON "app"."tasks" USING btree ("assignee_id","work_status","id");
