SET LOCAL ROLE app_owner;

-- ADR-032：接入立镖 Casdoor OIDC 单点登录（expand 迁移，不删除任何既有列）。
--
-- 1) app.users 增加 sso_subject（Casdoor 的 sub）：唯一、可空，且绑定后不得改写
--    或清空，防止换绑接管账号；
-- 2) password_hash 允许为空：SSO 自动开通的账号没有本地口令，本地隐藏入口
--    /login?local=1 仍只服务已持有口令的管理员；
-- 3) 新增 app.sso_login_attempts：只保存 state 的 HMAC-SHA-256 哈希、return_to
--    与过期时间；nonce 与 PKCE code_verifier 由服务端用同一 keyring 从 state
--    派生，因此没有任何可重放材料落库。

ALTER TABLE app.users ADD COLUMN sso_subject TEXT;

CREATE UNIQUE INDEX users_sso_subject_unique
  ON app.users (sso_subject)
  WHERE sso_subject IS NOT NULL;

ALTER TABLE app.users
  ADD CONSTRAINT users_sso_subject_check
  CHECK (sso_subject IS NULL OR length(btrim(sso_subject)) BETWEEN 1 AND 200);

CREATE FUNCTION app.reject_sso_subject_rebinding()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app
AS $function$
BEGIN
  IF OLD.sso_subject IS NOT NULL
     AND NEW.sso_subject IS DISTINCT FROM OLD.sso_subject THEN
    RAISE EXCEPTION 'users.sso_subject cannot be rebound once set'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$function$;

REVOKE ALL ON FUNCTION app.reject_sso_subject_rebinding() FROM PUBLIC;

CREATE TRIGGER users_sso_subject_rebind_guard
BEFORE UPDATE ON app.users
FOR EACH ROW EXECUTE FUNCTION app.reject_sso_subject_rebinding();

ALTER TABLE app.users ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE app.users DROP CONSTRAINT users_password_hash_check;
ALTER TABLE app.users
  ADD CONSTRAINT users_password_hash_check
  CHECK (password_hash IS NULL OR length(password_hash) BETWEEN 20 AND 1024);

ALTER TABLE app.users DROP CONSTRAINT users_password_algorithm_check;
ALTER TABLE app.users
  ADD CONSTRAINT users_password_algorithm_check
  CHECK (password_hash IS NULL OR password_hash LIKE '$argon2id$%');

CREATE TABLE app.sso_login_attempts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
    sequence name app.sso_login_attempts_id_seq
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1
  ),
  state_hash BYTEA NOT NULL,
  state_hash_key_version SMALLINT NOT NULL,
  return_to TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  CONSTRAINT sso_login_attempts_state_hash_unique UNIQUE (state_hash),
  CONSTRAINT sso_login_attempts_state_hash_check
    CHECK (octet_length(state_hash) = 32),
  CONSTRAINT sso_login_attempts_key_version_check
    CHECK (state_hash_key_version > 0),
  CONSTRAINT sso_login_attempts_return_to_check
    CHECK (return_to IS NULL OR length(return_to) BETWEEN 1 AND 2000),
  CONSTRAINT sso_login_attempts_expiry_check
    CHECK (
      expires_at > created_at
      AND expires_at <= created_at + INTERVAL '15 minutes'
    ),
  CONSTRAINT sso_login_attempts_consumed_check
    CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX sso_login_attempts_cleanup_idx
  ON app.sso_login_attempts (expires_at, id);

GRANT SELECT, INSERT, UPDATE, DELETE ON app.sso_login_attempts TO app_runtime;
GRANT USAGE, SELECT ON SEQUENCE app.sso_login_attempts_id_seq TO app_runtime;
