SET LOCAL ROLE app_owner;

-- F-06.2 项目归档申请（ADR-034）：除普通成员外的项目内管理角色
-- （组长、项目管理员）与系统管理员可发起项目归档申请。申请本身不改变项目状态，
-- 只有系统管理员批准时才会在同一事务内归档项目。申请前要求项目处于 ACTIVE
-- 且项目下没有未完成任务，同一项目同时只允许一条待审申请。

CREATE TABLE app.project_archive_requests (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
    sequence name app.project_archive_requests_id_seq
    INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1
  ),
  project_id integer NOT NULL REFERENCES app.projects (id),
  requested_by integer NOT NULL REFERENCES app.users (id),
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  decided_at TIMESTAMPTZ,
  decided_by integer REFERENCES app.users (id),
  decision_note TEXT,
  row_version INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT project_archive_requests_status_check
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED')),
  CONSTRAINT project_archive_requests_reason_check
    CHECK (length(btrim(reason)) BETWEEN 1 AND 2000),
  CONSTRAINT project_archive_requests_decision_note_check
    CHECK (
      decision_note IS NULL OR length(btrim(decision_note)) BETWEEN 1 AND 2000
    ),
  CONSTRAINT project_archive_requests_decision_check
    CHECK (
      (
        status = 'PENDING'
        AND decided_at IS NULL
        AND decided_by IS NULL
        AND decision_note IS NULL
      )
      OR (
        status <> 'PENDING'
        AND decided_at IS NOT NULL
        AND decided_by IS NOT NULL
      )
    ),
  CONSTRAINT project_archive_requests_row_version_check
    CHECK (row_version > 0)
);

-- 同一项目同一时刻只允许一条待审申请；并发重复申请由该唯一索引兜底 409。
CREATE UNIQUE INDEX project_archive_requests_one_pending
  ON app.project_archive_requests (project_id)
  WHERE status = 'PENDING';

CREATE INDEX project_archive_requests_project_idx
  ON app.project_archive_requests (project_id, requested_at DESC, id DESC);

-- 系统管理员待审列表按提交时间倒序读取。
CREATE INDEX project_archive_requests_pending_idx
  ON app.project_archive_requests (requested_at DESC, id DESC)
  WHERE status = 'PENDING';

-- 申请是业务历史：归属、申请人与申请理由不可改写，且不提供物理删除
-- （app_runtime 不持有 DELETE 授权），状态流转只更新决定列。
CREATE FUNCTION app.reject_project_archive_request_rebinding()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, app
AS $function$
BEGIN
  IF NEW.project_id IS DISTINCT FROM OLD.project_id
     OR NEW.requested_by IS DISTINCT FROM OLD.requested_by
     OR NEW.requested_at IS DISTINCT FROM OLD.requested_at
     OR NEW.reason IS DISTINCT FROM OLD.reason THEN
    RAISE EXCEPTION 'project archive request origin cannot be rewritten'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$function$;

REVOKE ALL ON FUNCTION app.reject_project_archive_request_rebinding() FROM PUBLIC;

CREATE TRIGGER project_archive_requests_origin_guard
BEFORE UPDATE ON app.project_archive_requests
FOR EACH ROW EXECUTE FUNCTION app.reject_project_archive_request_rebinding();

GRANT SELECT, INSERT, UPDATE ON app.project_archive_requests TO app_runtime;
GRANT USAGE, SELECT ON SEQUENCE app.project_archive_requests_id_seq TO app_runtime;
